-- Seed data for Executive Intelligence System
-- Run after schema.sql in Supabase SQL Editor

DO $$
DECLARE
  v_report_id UUID;
BEGIN
  INSERT INTO reports (report_date, raw_content, summary, generated_at)
  VALUES (
    CURRENT_DATE,
    'Daily Executive Intelligence Report — Generated by Cowork AI at 20:00 GYT. This report covers operational status, strategic objectives, active risks, and key metrics across all business units. Revenue targets are tracking ahead of schedule. Two critical items require immediate executive attention: the API infrastructure migration deadline and the enterprise client renewal at risk. Team velocity has improved 12% week-over-week. Email backlog is manageable but growing. Three strategic objectives are on track, with one requiring intervention on the operational side.',
    'Two critical items require attention: API migration deadline (tomorrow) and enterprise client renewal at risk. Revenue tracking ahead of Q1 target. Team velocity up 12% WoW. One operational objective behind schedule.',
    now()
  )
  RETURNING id INTO v_report_id;

  -- Risks
  INSERT INTO risks (report_id, title, description, severity, category, mitigation) VALUES
  (v_report_id, 'API infrastructure migration deadline at risk', 'Migration to new API gateway must complete by end of week. Current progress at 60%. Team capacity constrained by parallel project demands.', 'critical', 'Engineering', 'Reallocate two engineers from feature work. Defer non-critical deployments until migration complete.'),
  (v_report_id, 'Enterprise client renewal — Meridian Corp', 'Annual renewal ($240K ARR) showing signs of churn risk. Champion left the organization last month. New stakeholder requesting competitive evaluation.', 'high', 'Revenue', 'Schedule executive-to-executive call this week. Prepare ROI deck with usage data. Offer early renewal incentive.'),
  (v_report_id, 'Operational cost increase in cloud infrastructure', 'Monthly cloud spend increased 18% due to unoptimized batch processing jobs. Trend will exceed budget by Q2 if unchecked.', 'medium', 'Operations', 'Initiate cost optimization sprint. Review and consolidate unused resources. Implement auto-scaling policies.');

  -- Tasks
  INSERT INTO tasks (report_id, title, description, priority, category, due_date) VALUES
  (v_report_id, 'Review and approve API migration rollback plan', 'Engineering team needs sign-off on the rollback strategy before proceeding with final migration phase.', 'critical', 'Engineering', CURRENT_DATE),
  (v_report_id, 'Call Meridian Corp new stakeholder', 'Introductory call with new VP of Product at Meridian. Prepare talking points around platform value and roadmap alignment.', 'high', 'Revenue', CURRENT_DATE),
  (v_report_id, 'Review Q1 financial close documents', 'Finance team has prepared preliminary Q1 close. Review revenue recognition and deferred revenue entries.', 'high', 'Finance', CURRENT_DATE + INTERVAL '1 day'),
  (v_report_id, 'Approve hiring plan for Q2', 'Three positions pending approval: Senior Engineer, Product Designer, Customer Success Manager.', 'medium', 'People', CURRENT_DATE + INTERVAL '3 days'),
  (v_report_id, 'Prepare board update presentation', 'Monthly board update covering KPIs, strategic initiatives, and capital allocation. Due next week.', 'medium', 'Strategy', CURRENT_DATE + INTERVAL '5 days'),
  (v_report_id, 'Review cloud cost optimization proposals', 'Operations team has identified three cost reduction opportunities. Review and prioritize for implementation.', 'low', 'Operations', CURRENT_DATE + INTERVAL '7 days');

  -- Objectives
  INSERT INTO objectives (report_id, title, description, type, status, due_date, notes) VALUES
  (v_report_id, 'Achieve $1.2M ARR by end of Q1', 'Close remaining pipeline deals and secure three enterprise renewals to hit quarterly revenue target.', 'revenue', 'on_track', CURRENT_DATE + INTERVAL '30 days', 'Currently at $1.08M. Pipeline coverage at 1.4x. Two deals in final negotiation.'),
  (v_report_id, 'Complete platform reliability upgrade', 'Achieve 99.95% uptime SLA through infrastructure modernization and monitoring improvements.', 'operational', 'behind', CURRENT_DATE + INTERVAL '14 days', 'API migration delay impacting timeline. Monitoring stack 80% deployed. Need to accelerate final phase.'),
  (v_report_id, 'Launch partner ecosystem program', 'Establish integration partnerships with three complementary platforms to expand market reach.', 'strategic', 'on_track', CURRENT_DATE + INTERVAL '60 days', 'Two LOIs signed. Third partnership in discussion phase. Developer documentation 70% complete.'),
  (v_report_id, 'Expand to EMEA market', 'Establish initial presence in European market with first three enterprise clients and local support capability.', 'growth', 'at_risk', CURRENT_DATE + INTERVAL '90 days', 'Regulatory review taking longer than expected. First prospect meeting scheduled for next month.');

  -- Metrics
  INSERT INTO metrics (report_id, label, value, unit, change_direction) VALUES
  (v_report_id, 'Unread Emails', 23, 'emails', 'up'),
  (v_report_id, 'Active Sessions', 847, 'users', 'up'),
  (v_report_id, 'Active Tasks', 12, 'items', 'stable'),
  (v_report_id, 'Monthly Revenue', 89400, 'USD', 'up');
END $$;
